version: "3.8"
services:
  weaselbot:
    image: weas/weaselbot:latest
    env_file:
      - ./.env
    volumes:
      - ./data:/app/data
    deploy:
      restart_policy:
        condition: any
        delay: 120s
        max_attempts: 3
        window: 60s